
// This file has been generated by the GUI designer. Do not modify.
namespace Comando
{
	public partial class WidgetConsole
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView _textfieldOutput;

		private global::Gtk.Entry _inputGenericCommand;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Comando.WidgetConsole
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 500;
			this.Name = "Comando.WidgetConsole";
			// Container child Comando.WidgetConsole.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.Yalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Output");
			this.vbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this._textfieldOutput = new global::Gtk.TextView();
			this._textfieldOutput.WidthRequest = 300;
			this._textfieldOutput.CanFocus = true;
			this._textfieldOutput.Name = "_textfieldOutput";
			this._textfieldOutput.Editable = false;
			this._textfieldOutput.CursorVisible = false;
			this._textfieldOutput.AcceptsTab = false;
			this._textfieldOutput.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add(this._textfieldOutput);
			this.vbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this._inputGenericCommand = new global::Gtk.Entry();
			this._inputGenericCommand.CanFocus = true;
			this._inputGenericCommand.Name = "_inputGenericCommand";
			this._inputGenericCommand.IsEditable = true;
			this._inputGenericCommand.InvisibleChar = '●';
			this.vbox2.Add(this._inputGenericCommand);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this._inputGenericCommand]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
