
// This file has been generated by the GUI designer. Do not modify.
namespace Comando
{
	public partial class WindowAddExposedCommand
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label _labelTittle;

		private global::Gtk.Entry _inputCommand;

		private global::Gtk.Entry _inputTittle;

		private global::Gtk.Label _labelCommand;

		private global::Gtk.Label _labelCommandTittle1;

		private global::Gtk.Button _buttonAccept;

		private global::Gtk.Button _commandPickerButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Comando.WindowAddExposedCommand
			this.Name = "Comando.WindowAddExposedCommand";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowAddExposedCommand");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Comando.WindowAddExposedCommand.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._labelTittle = new global::Gtk.Label();
			this._labelTittle.Name = "_labelTittle";
			this._labelTittle.LabelProp = global::Mono.Unix.Catalog.GetString("New command");
			this.fixed4.Add(this._labelTittle);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._labelTittle]));
			w1.X = 8;
			w1.Y = 7;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._inputCommand = new global::Gtk.Entry();
			this._inputCommand.WidthRequest = 200;
			this._inputCommand.CanFocus = true;
			this._inputCommand.Name = "_inputCommand";
			this._inputCommand.IsEditable = true;
			this._inputCommand.InvisibleChar = '●';
			this.fixed4.Add(this._inputCommand);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._inputCommand]));
			w2.X = 175;
			w2.Y = 76;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._inputTittle = new global::Gtk.Entry();
			this._inputTittle.CanFocus = true;
			this._inputTittle.Name = "_inputTittle";
			this._inputTittle.IsEditable = true;
			this._inputTittle.InvisibleChar = '●';
			this.fixed4.Add(this._inputTittle);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._inputTittle]));
			w3.X = 10;
			w3.Y = 76;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._labelCommand = new global::Gtk.Label();
			this._labelCommand.Name = "_labelCommand";
			this._labelCommand.LabelProp = global::Mono.Unix.Catalog.GetString("Command");
			this.fixed4.Add(this._labelCommand);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._labelCommand]));
			w4.X = 177;
			w4.Y = 52;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._labelCommandTittle1 = new global::Gtk.Label();
			this._labelCommandTittle1.Name = "_labelCommandTittle1";
			this._labelCommandTittle1.LabelProp = global::Mono.Unix.Catalog.GetString("Tittle");
			this.fixed4.Add(this._labelCommandTittle1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._labelCommandTittle1]));
			w5.X = 14;
			w5.Y = 52;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._buttonAccept = new global::Gtk.Button();
			this._buttonAccept.WidthRequest = 150;
			this._buttonAccept.HeightRequest = 40;
			this._buttonAccept.CanFocus = true;
			this._buttonAccept.Name = "_buttonAccept";
			this._buttonAccept.UseUnderline = true;
			this._buttonAccept.Label = global::Mono.Unix.Catalog.GetString("Accept");
			this.fixed4.Add(this._buttonAccept);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._buttonAccept]));
			w6.X = 13;
			w6.Y = 110;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._commandPickerButton = new global::Gtk.Button();
			this._commandPickerButton.CanFocus = true;
			this._commandPickerButton.Name = "_commandPickerButton";
			this._commandPickerButton.UseUnderline = true;
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Button);
			this._commandPickerButton.Image = w7;
			this.fixed4.Add(this._commandPickerButton);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._commandPickerButton]));
			w8.X = 375;
			w8.Y = 67;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 443;
			this.DefaultHeight = 199;
			this.Show();
			this._buttonAccept.Clicked += new global::System.EventHandler(this.OnAddNewCommandButtonClick);
			this._commandPickerButton.Clicked += new global::System.EventHandler(this.OnCommandPickerButtonClick);
		}
	}
}
