
// This file has been generated by the GUI designer. Do not modify.
namespace Comando
{
	public partial class WindowCommandList
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView _commandsTree;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Comando.WindowCommandList
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "Comando.WindowCommandList";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowCommandList");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Comando.WindowCommandList.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this._commandsTree = new global::Gtk.TreeView();
			this._commandsTree.CanFocus = true;
			this._commandsTree.Name = "_commandsTree";
			this.GtkScrolledWindow.Add(this._commandsTree);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			this.Show();
		}
	}
}
