
// This file has been generated by the GUI designer. Do not modify.
namespace Comando
{
	public partial class WindowHostTargets
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.Button _buttonAccept;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.Fixed _hostTargetsCanvas;

		private global::Gtk.Button _buttonAddhostEntry;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Comando.WindowHostTargets
			this.Name = "Comando.WindowHostTargets";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowHostTargets");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Comando.WindowHostTargets.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this._buttonAccept = new global::Gtk.Button();
			this._buttonAccept.CanFocus = true;
			this._buttonAccept.Name = "_buttonAccept";
			this._buttonAccept.UseUnderline = true;
			this._buttonAccept.Label = global::Mono.Unix.Catalog.GetString("Accept");
			this.fixed4.Add(this._buttonAccept);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this._buttonAccept]));
			w1.X = 6;
			w1.Y = 208;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 500;
			this.GtkScrolledWindow.HeightRequest = 200;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this._hostTargetsCanvas = new global::Gtk.Fixed();
			this._hostTargetsCanvas.WidthRequest = 300;
			this._hostTargetsCanvas.HeightRequest = 150;
			this._hostTargetsCanvas.Name = "_hostTargetsCanvas";
			this._hostTargetsCanvas.HasWindow = false;
			// Container child _hostTargetsCanvas.Gtk.Fixed+FixedChild
			this._buttonAddhostEntry = new global::Gtk.Button();
			this._buttonAddhostEntry.CanFocus = true;
			this._buttonAddhostEntry.Name = "_buttonAddhostEntry";
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Button);
			this._buttonAddhostEntry.Image = w3;
			this._hostTargetsCanvas.Add(this._buttonAddhostEntry);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this._hostTargetsCanvas[this._buttonAddhostEntry]));
			w4.X = 35;
			w4.Y = 67;
			w2.Add(this._hostTargetsCanvas);
			this.GtkScrolledWindow.Add(w2);
			this.fixed4.Add(this.GtkScrolledWindow);
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 241;
			this.Show();
			this._buttonAccept.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnAddHostTargetsButtonPress);
			this._buttonAddhostEntry.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnAddHostButtonPress);
		}
	}
}
