
// This file has been generated by the GUI designer. Do not modify.
namespace Comando
{
	public partial class WindowCommandsTooltip
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label CommandText;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Comando.WindowCommandsTooltip
			this.Name = "Comando.WindowCommandsTooltip";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			// Container child Comando.WindowCommandsTooltip.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CommandText = new global::Gtk.Label();
			this.CommandText.Name = "CommandText";
			this.CommandText.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed1.Add(this.CommandText);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.CommandText]));
			w1.Y = 7;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 223;
			this.DefaultHeight = 99;
			this.Show();
		}
	}
}
