
// This file has been generated by the GUI designer. Do not modify.
namespace Comando
{
	public partial class WindowPrompt
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label _description;

		private global::Gtk.Button _buttonAccept;

		private global::Gtk.Button _buttonCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Comando.WindowPrompt
			this.Name = "Comando.WindowPrompt";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowPrompt");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Comando.WindowPrompt.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this._description = new global::Gtk.Label();
			this._description.WidthRequest = 300;
			this._description.HeightRequest = 60;
			this._description.Name = "_description";
			this._description.Yalign = 0F;
			this._description.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this._description.Wrap = true;
			this.fixed3.Add(this._description);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this._description]));
			w1.X = 2;
			w1.Y = 3;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this._buttonAccept = new global::Gtk.Button();
			this._buttonAccept.WidthRequest = 80;
			this._buttonAccept.HeightRequest = 30;
			this._buttonAccept.CanFocus = true;
			this._buttonAccept.Name = "_buttonAccept";
			this._buttonAccept.UseUnderline = true;
			this._buttonAccept.Label = global::Mono.Unix.Catalog.GetString("Accept");
			this.fixed3.Add(this._buttonAccept);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this._buttonAccept]));
			w2.X = 4;
			w2.Y = 53;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this._buttonCancel = new global::Gtk.Button();
			this._buttonCancel.WidthRequest = 80;
			this._buttonCancel.HeightRequest = 30;
			this._buttonCancel.CanFocus = true;
			this._buttonCancel.Name = "_buttonCancel";
			this._buttonCancel.UseUnderline = true;
			this._buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.fixed3.Add(this._buttonCancel);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this._buttonCancel]));
			w3.X = 88;
			w3.Y = 53;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 322;
			this.DefaultHeight = 104;
			this.Show();
			this._buttonAccept.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnAcceptButtonPress);
			this._buttonCancel.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnCancelButtonPress);
		}
	}
}
